# Generated by Django 5.1.5 on 2025-02-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('car', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('diagnostics', 'Диагностика автомобиля'), ('engine_repair', 'Ремонт двигателя и трансмиссии'), ('maintenance', 'Замена масла и техническое обслуживание'), ('body_repair', 'Кузовной ремонт и покраска'), ('tire_change', 'Замена шин и балансировка'), ('ac_service', 'Обслуживание кондиционера')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
