# Generated by Django 5.1.5 on 2025-02-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Запись на услугу', 'verbose_name_plural': 'Записи на услуги'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='car',
            field=models.CharField(max_length=100, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('diagnostics', 'Диагностика автомобиля'), ('engine_repair', 'Ремонт двигателя и трансмиссии'), ('maintenance', 'Замена масла и техническое обслуживание'), ('body_repair', 'Кузовной ремонт и покраска'), ('tire_change', 'Замена шин и балансировка'), ('ac_service', 'Обслуживание кондиционера')], max_length=20, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
    ]
