# Generated by Django 5.1.5 on 2025-02-02 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appointment_last_modified_statuschangelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuschangelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Изменение статуса', 'verbose_name_plural': 'История изменений статусов'},
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='main.appointment', verbose_name='Заявка'),
        ),
    ]
